# 华为实习笔记

In [5]:
import numpy as np

## list 切片

### Example 1

In [8]:
list_l = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
list_ndarry = np.array(list_l)
# 第一个1：3是取最外层括号的1：3， 第二个1：3是取第二层括号的1：3; list_t是一个array
list_t = list_ndarry[1:3, 1:3]
# list_t2是一个元素为list的list
list_t2 = [ list_l[i][1:3] for i in range(1,3) ]

print(list_t)
print(list_t2)
print("t element:{}".format(list_t[0]))
print("t2 element:{}".format(list_t2[0]))

[[ 6  7]
 [10 11]]
[[6, 7], [10, 11]]
t element:[6 7]
t2 element:[6, 7]


### Example 2

In [13]:
test_arr = np.arange(0,50)
test_arr = test_arr.reshape(5,10)
test_list = test_arr.tolist()
print(test_list)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [16]:
# 取除第一列外的其他所有元素
# res = test_list[:][1:]   # 错误，test_list[:]=test_list
# res = test_list[:,1:]    # 错误，不能对list对象多为切片，list indices must be integers or slices, not tuple
res=[]
for elem in test_list:
    res.append(elem[1:])
print(res)  
res = test_arr[:,1:]    # 正确，对array可以进行多维切片
print(res)

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [11, 12, 13, 14, 15, 16, 17, 18, 19], [21, 22, 23, 24, 25, 26, 27, 28, 29], [31, 32, 33, 34, 35, 36, 37, 38, 39], [41, 42, 43, 44, 45, 46, 47, 48, 49]]
[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]
 [21 22 23 24 25 26 27 28 29]
 [31 32 33 34 35 36 37 38 39]
 [41 42 43 44 45 46 47 48 49]]


## Class对象

In [18]:
class Dog():
    def __init__(self, name, age):   # __init__为构造方法
        self.name = name   # self类似this，定义成员变量或成员方法
        self.age = age
    
    # 成员方法第一个参数必须是'self'，只能通过实例调用
    def introduce(self):
        print("This dog is " + self.name + ", whose age is " + str(self.age))
        
    # 类方法以cls作为第一个参数，cls表示类本身，定义时使用@classmethod装饰器
    @classmethod
    def cls_info(cls):
        # 通过cls可以访问类的相关属性
        print("调用类方法：类名{}".format(cls.__name__))
        
    # 静态方法装饰器，没有参数限制，不需实例参数，不需类参数
    @staticmethod
    def static_info():
        print("调用静态方法")
        
myDog = Dog('March',3)
myDog.introduce()

# 类方法和静态方法都可以用类或者实例调用
Dog.cls_info()
myDog.cls_info()
Dog.static_info()
myDog.static_info()

This dog is March, whose age is 3
调用类方法：类名Dog
调用类方法：类名Dog
调用静态方法
调用静态方法


### 继承

In [21]:
class Teddy(Dog):
    def __init__(self, name, age):
#         super.__init__(name, age)   # super()函数用于调用父类（）超类的方法
        Dog.__init__(self, name, age)   # 直接调用父类的构造方法
        self.hasParent = True
    
    def introduce(self):   # 重写父类方法
        print("This teddy is " + self.name + ", whose age is " + str(self.age))
        
    def attention(self):
        print("Teddy is f your house. Really? {}".format(self.hasParent))
        
myDog = Teddy('April', 2)
myDog.introduce()
myDog.attention()

# 类方法和静态方法都可以继承
myDog.cls_info()
myDog.static_info()

This teddy is April, whose age is 2
Teddy is f your house. Really? True
调用类方法：类名Teddy
调用静态方法
